name: Deploy and Run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust the version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build and Run
        run: |
          node index.js &
          npx http-server . -p ${{ github.event.inputs.port || 8080 }}
